//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV.Frm {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLSV.Frm.FormResource", typeof(FormResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã nhập sai tên đăng nhập hoặc mật khẩu
        ///Xin vui lòng thử lại.
        /// </summary>
        internal static string FrmDangNhap_Dangnhap_ {
            get {
                return ResourceManager.GetString("FrmDangNhap_Dangnhap_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string MsgCaption {
            get {
                return ResourceManager.GetString("MsgCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chọn sai chức năng!.
        /// </summary>
        internal static string Msgchonchucnang {
            get {
                return ResourceManager.GetString("Msgchonchucnang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn phải chọn file excel..
        /// </summary>
        internal static string msgChonFileExcel {
            get {
                return ResourceManager.GetString("msgChonFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dung lượng file upload quá lớn, dung lượng tối đa cho phép là 20MB..
        /// </summary>
        internal static string msgFileQuaLon {
            get {
                return ResourceManager.GetString("msgFileQuaLon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc chắn muốn xóa không?.
        /// </summary>
        internal static string msgHoixoa {
            get {
                return ResourceManager.GetString("msgHoixoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã chọn nhầm file hoặc file đang được mở.
        /// </summary>
        internal static string msgKiemTraFile {
            get {
                return ResourceManager.GetString("msgKiemTraFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection to SQL Server.
        /// </summary>
        internal static string msgLostConnect {
            get {
                return ResourceManager.GetString("msgLostConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trong file không đúng quy định.
        /// </summary>
        internal static string msgSaiDuLieuTrongFile {
            get {
                return ResourceManager.GetString("msgSaiDuLieuTrongFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiếu cột trong file excel.
        /// </summary>
        internal static string msgThieuCotTrongFile {
            get {
                return ResourceManager.GetString("msgThieuCotTrongFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có muốn thoát chương trình không?.
        /// </summary>
        internal static string msgThoat {
            get {
                return ResourceManager.GetString("msgThoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu lại thành công.
        /// </summary>
        internal static string MsgThongbaothanhcong {
            get {
                return ResourceManager.GetString("MsgThongbaothanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toàn bộ sinh viên thuộc lớp sẽ bị xóa.
        /// Bạn có muốn xóa không ?.
        /// </summary>
        internal static string MsgThongbaoxoalop {
            get {
                return ResourceManager.GetString("MsgThongbaoxoalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh viên thuộc lớp không thể xóa.
        ///Cần xóa sinh viên trước khi xóa lớp..
        /// </summary>
        internal static string Msgthongbaoxoalop2 {
            get {
                return ResourceManager.GetString("Msgthongbaoxoalop2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa Thành công.
        /// </summary>
        internal static string msgThongbaoxoathanhcong {
            get {
                return ResourceManager.GetString("msgThongbaoxoathanhcong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả sinh viên đã được xếp phòng
        ///Thêm mới sinh viên hoặc xóa sinh viên đã xếp phòng.
        /// </summary>
        internal static string msgxepphong {
            get {
                return ResourceManager.GetString("msgxepphong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/mm/yyyy.
        /// </summary>
        internal static string txtddmmyyyy {
            get {
                return ResourceManager.GetString("txtddmmyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Files|*.xls;*.xlsx;*.xlsm.
        /// </summary>
        internal static string txtDuoiFileExcel {
            get {
                return ResourceManager.GetString("txtDuoiFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20000000.
        /// </summary>
        internal static string txtFileSize {
            get {
                return ResourceManager.GetString("txtFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ.
        /// </summary>
        internal static string txtHosinhvien {
            get {
                return ResourceManager.GetString("txtHosinhvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoa.
        /// </summary>
        internal static string txtKhoaquanly {
            get {
                return ResourceManager.GetString("txtKhoaquanly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không kết nối được đến Cơ sở dữ liệu.
        /// </summary>
        internal static string txtLoiDB {
            get {
                return ResourceManager.GetString("txtLoiDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khoa.
        /// </summary>
        internal static string txtMakhoa {
            get {
                return ResourceManager.GetString("txtMakhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kỳ thi.
        /// </summary>
        internal static string txtMakythi {
            get {
                return ResourceManager.GetString("txtMakythi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Lớp.
        /// </summary>
        internal static string txtMalop {
            get {
                return ResourceManager.GetString("txtMalop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã sinh viên.
        /// </summary>
        internal static string txtMasinhvien {
            get {
                return ResourceManager.GetString("txtMasinhvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        internal static string txtMatKhau {
            get {
                return ResourceManager.GetString("txtMatKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mở file excell..
        /// </summary>
        internal static string txtMoFileExcel {
            get {
                return ResourceManager.GetString("txtMoFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày thi.
        /// </summary>
        internal static string txtNgaythi {
            get {
                return ResourceManager.GetString("txtNgaythi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền.
        /// </summary>
        internal static string txtQuyen {
            get {
                return ResourceManager.GetString("txtQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang xử lý ....
        /// </summary>
        internal static string txtRunning {
            get {
                return ResourceManager.GetString("txtRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên khoa.
        /// </summary>
        internal static string txtTenkhoa {
            get {
                return ResourceManager.GetString("txtTenkhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kỳ thi.
        /// </summary>
        internal static string txtTenkythi {
            get {
                return ResourceManager.GetString("txtTenkythi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng.
        /// </summary>
        internal static string txtTenNguoiDung {
            get {
                return ResourceManager.GetString("txtTenNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string txtTensinhvien {
            get {
                return ResourceManager.GetString("txtTensinhvien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản.
        /// </summary>
        internal static string txtTenTaiKhoan {
            get {
                return ResourceManager.GetString("txtTenTaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu.
        /// </summary>
        internal static string txtThoigianbatdau {
            get {
                return ResourceManager.GetString("txtThoigianbatdau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian kết thúc.
        /// </summary>
        internal static string txtThoigianketthuc {
            get {
                return ResourceManager.GetString("txtThoigianketthuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian làm bài.
        /// </summary>
        internal static string txtThoigianlambai {
            get {
                return ResourceManager.GetString("txtThoigianlambai", resourceCulture);
            }
        }
    }
}
